#!/bin/bash

sudo rm /usr/share/glib-2.0/schemas/linuxmint.mgse.*.gschema.xml

sudo rm -rf /usr/share/gnome-shell/extensions/menu@linuxmint.com
sudo cp -R mgse-menu/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/windowlist@linuxmint.com
sudo cp -R mgse-windowlist/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/windowlist@linuxmint.com
sudo cp -R mgse-windowlist/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/noa11y@linuxmint.com
sudo cp -R mgse-noa11y/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/mediaplayer@linuxmint.com
sudo cp -R mgse-mediaplayer/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/xrandr@linuxmint.com
sudo cp -R mgse-xrandr/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/userthemes@linuxmint.com
sudo cp -R mgse-userthemes/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/smartoverview@linuxmint.com
sudo cp -R mgse-smartoverview/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/shutdownmenu@linuxmint.com
sudo cp -R mgse-shutdownmenu/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/alttab@linuxmint.com
sudo cp -R mgse-alttab/usr /

sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
