#!/bin/bash

sudo rm -rf /usr/share/gnome-shell/extensions/menu@linuxmint.com
sudo cp -R mgse-menu/usr /

sudo rm -rf /usr/share/gnome-shell/extensions/windowlist@linuxmint.com
sudo cp -R mgse-windowlist/usr /
