#!/bin/bash

sudo rm -rf /usr/share/gnome-shell/extensions/userthemes@linuxmint.com
sudo rm /usr/share/glib-2.0/schemas/linuxmint.mgse.userthemes.gschema.xml
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
