#!/bin/bash

sudo rm -rf /usr/share/gnome-shell/extensions/alttab@linuxmint.com
sudo rm /usr/share/glib-2.0/schemas/org.gnome.shell.extensions.alternate-tab.gschema.xml
sudo cp -R usr /
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
